### ISSUE TITLE
Embedded tweets broken in the CRAN resources post

### ISSUE THREAD

**Issue by maelle** [ivelasq/pipedream#8]
:wave: @ivelasq! I was looking at https://ivelasq.rbind.io/blog/you-cran-do-it/ that I'm linking from https://http-testing-r.netlify.app/resources/#cran-submissions

Actually now I see you've tried to fix the problem! Ouch, such problems are not fun. Maybe you could try changing the `.type` argument i.e. `blogdown::shortcode("tweet", "1234567", .type = "html")`?

**Comment by ivelasq** [comment]
Hi Maëlle! Thanks for taking a look. It seems to be a bug, perhaps because of the newest version of Hugo :( I posted about the issue [here](https://community.rstudio.com/t/hugo-blogdown-twitter-shortcode-not-rendering/106550). I tried `.type = "html"` but it looks like this: `{{< tweet "1228139634871472129" >}}`. Welcome any other ideas, hope to get it sorted out soon! Thanks again.

**Comment by maelle** [comment]
but `{{< tweet "1228139634871472129" >}}` actually works for https://ivelasq.rbind.io/blog/creating-a-new-theme/ (source https://github.com/ivelasq/pipedream/blob/2a1e3bb4e7957c8fcc8c58ed130d9b04f8971029/content/blog/creating-a-new-theme.md#L87)?

**Comment by maelle** [comment]
I actually understand whay you were saying, sorry. 

By the way why do you render to html as opposed to Markdown?

**Comment by ivelasq** [comment]
No particular reason, I think it's the default and I never changed it.

**Comment by ivelasq** [comment]
I changed the method to `markdown` and now everything is rendering! Thanks so much - I really appreciate it!

**Comment by maelle** [comment]
Fantastic! 🎉
